# Generated by Django 5.2.11 on 2026-03-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0002_work_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikicfp_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('event_date', models.DateField(blank=True, db_index=True, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conferences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
