# Generated by Django 5.2.11 on 2026-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0004_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="clean_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conference",
            name="deadline_raw",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="conference",
            name="event_date_raw",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="conference",
            name="is_processed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="conference",
            name="last_collected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conference",
            name="raw_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
