# Generated by Django 5.2.11 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0005_conference_clean_description_conference_deadline_raw_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(fields=["is_processed", "-event_date"], name="conf_proc_event_idx"),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(fields=["-event_date", "-id"], name="conf_event_id_idx"),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(fields=["deadline", "is_processed"], name="conf_deadline_proc_idx"),
        ),
    ]
